version: 1.0.{build}
image: Visual Studio 2017
install:
  - ps: choco install -y miktex
  - cmd:  refreshenv

build_script:
  - cmd: pdflatex .\deadlift.tex -output-directory=output
  - path: output

artifacts:
  - path: output\*.pdf

deploy:
  - provider: GitHub
    artifact: output\*.pdf
    on:
      branch: master